
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[RPTSALESMARGINANALYSIS]
		@DATEFROM = 20171201,
		@DATETO = 20171215,
		@COSTINGMETHOD = N'WA',
		@TRANSACTIONMETHOD = 0,
		@COSTINGOPTION = 8,
		@INCLUDEDN = 0,
		@INCLUDECN = 0,
		@INCLUDECASHSALES = 1,
		@INCLUDEDATA = 1,
		@INCLUDEGRN = 'Y',
		@INCLUDESA = 'Y',
		@INCLUDESTOCKITEM = 'Y',
		@STOCKITEMFROM = '',
		@STOCKITEMTO = '',
		@INCLUDESERVICEITEM = 'Y',
		@SERVICEITEMFROM = '',
		@SERVICEITEMTO = '',
		@INCLUDESTOCKBUNDLED = 'N',
		@INCLUDESTOCKTRANSFER = 'Y',
		@INCLUDEGLOBALDISCOUNT = 'Y',
		@INCLUDEGLOBALSERVICETAX = 'N',
		@INCLUDEGLOBALMISCCHARGE = 'N',
		@TITLE = 'Sales Margin Analysis',
		@SALESINVOICEFROM = '',
		@SALESINVOICETO = '',
		@DNCODEFROM = '',
		@DNCODETO = '',
		@CNCODEFROM = '',
		@CNCODETO = '',
		@CASHSALESFROM = '',
		@CASHSALESTO = '',
		@CUSTOMERCODEFROM = '',
		@CUSTOMERCODETO = '',
		@STOCKCATEGORYFROM = '',
		@STOCKCATEGORYTO = '',
		@STOCKGROUPFROM = '',
		@STOCKGROUPTO = '',
		@STOCKCLASSFROM = '',
		@STOCKCLASSTO = '',
		@AGENTFROM = '',
		@AGENTTO = '',
		@ALLPROJECT = 1,
		@tblPROJECTCODE = Default,
		@FORMAT = 1,
		@INCLUDESINV = 1

SELECT	'Return Value' = @return_value

GO
